language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - './.cache'
    - './public'
    - node_modules
install: yarn
# before_script: sed -i "s|'/',|'/gatsby-starter-plone/',|" ./gatsby-config.js
script: 'yarn build --prefix-paths'
deploy:
  provider: pages
  github-token: '$GITHUB_TOKEN'
  local-dir: './public'
  target-branch: gh-pages
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
after_success:
  - 'npm run deploy'
